server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://192.168.241.129:3306/ctb?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: 123456
logging:
  file: me.log
  level:
    cn.*: debug
